package wifi_mapping.prototypes;

import cgresearch.core.math.Vector;
import cgresearch.ui.IApplicationControllerGui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by christian on 10.07.16.
 */
public class SpheresGUI extends IApplicationControllerGui implements ActionListener {

    private Spheres app;

    private JTextField rInnerTextField;
    private JTextField gInnerTextField;
    private JTextField bInnerTextField;
    private JTextField rOuterTextField;
    private JTextField gOuterTextField;
    private JTextField bOuterTextField;
    private JButton applyButton;
    private JPanel mainPanel;

    public SpheresGUI(Spheres app) {
        this.app = app;
        $$$setupUI$$$();
        applyButton.addActionListener(this);

        // Build the text fields
        Vector defaultInnerColour = app.getInnerColour();
        rInnerTextField.setText(Double.toString(defaultInnerColour.get(0)));
        gInnerTextField.setText(Double.toString(defaultInnerColour.get(1)));
        bInnerTextField.setText(Double.toString(defaultInnerColour.get(2)));

        Vector defaultOuterColour = app.getOuterColour();
        rOuterTextField.setText(Double.toString(defaultOuterColour.get(0)));
        gOuterTextField.setText(Double.toString(defaultOuterColour.get(1)));
        bOuterTextField.setText(Double.toString(defaultOuterColour.get(2)));
    }

    @Override
    public String getName() {
        return "Spheres";
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        double rInner = Double.parseDouble(rInnerTextField.getText());
        double gInner = Double.parseDouble(gInnerTextField.getText());
        double bInner = Double.parseDouble(bInnerTextField.getText());
        app.getInnerColour().set(rInner, gInner, bInner);

        double rOuter = Double.parseDouble(rOuterTextField.getText());
        double gOuter = Double.parseDouble(gOuterTextField.getText());
        double bOuter = Double.parseDouble(bOuterTextField.getText());
        app.getOuterColour().set(rOuter, gOuter, bOuter);

        // TODO change this to the observer pattern supported by CgApplication
        app.updateColour();
    }

    private void createUIComponents() {
        mainPanel = new JPanel();
        add(mainPanel);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel1, gbc);
        rInnerTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(rInnerTextField, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Inner Red");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel2, gbc);
        gInnerTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(gInnerTextField, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Inner Green");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel3, gbc);
        bInnerTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(bInnerTextField, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Inner Blue");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(label3, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel4, gbc);
        rOuterTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(rOuterTextField, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Outer Red");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(label4, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel5, gbc);
        gOuterTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel5.add(gOuterTextField, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Outer Green");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel5.add(label5, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel6, gbc);
        bOuterTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(bOuterTextField, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Outer Blue");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel6.add(label6, gbc);
        applyButton = new JButton();
        applyButton.setText("Apply");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(applyButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
